CHECKS = [
    {
        "check_id": "DISC-001",
        "title": "AS metadata reachability",
        "description": "Verifies the authorisation server publishes a reachable RFC 8414 metadata document.",
        "reference": "Hosseyni et al. (2025) — attacker token injection / client impersonation precondition.",
    },
    {
        "check_id": "DISC-002",
        "title": "Issuer identifier format",
        "description": "Checks that the metadata issuer is an HTTPS URL with no query string or fragment.",
        "reference": "RFC 9207 / FAPI 2.0 Security Profile — issuer identification.",
    },
    {
        "check_id": "DISC-003",
        "title": "PAR advertisement",
        "description": "Confirms pushed authorisation requests are advertised as required by FAPI 2.0.",
        "reference": "RFC 9126 PAR; FAPI 2.0 require_pushed_authorization_requests.",
    },
    {
        "check_id": "PAR-001",
        "title": "PAR bypass",
        "description": "Calls /authorize with front-channel parameters and no request_uri.",
        "reference": "RFC 9126; Hosseyni et al. (2025) §3.1–3.2.",
    },
    {
        "check_id": "PAR-002",
        "title": "request_uri replay",
        "description": "Uses the same request_uri twice at /authorize.",
        "reference": "RFC 9126 §2.2.",
    },
    {
        "check_id": "PKCE-001",
        "title": "Missing code_verifier",
        "description": "Exchanges an authorization code without a code_verifier.",
        "reference": "RFC 7636; FAPI 2.0.",
    },
    {
        "check_id": "PKCE-002",
        "title": "Plain PKCE method",
        "description": "Attempts PAR with code_challenge_method=plain.",
        "reference": "RFC 7636 S256.",
    },
    {
        "check_id": "AUTH-001",
        "title": "Client assertion replay",
        "description": "Reuses the same private_key_jwt client assertion twice.",
        "reference": "RFC 7523; FAPI 2.0.",
    },
    {
        "check_id": "AUTH-002",
        "title": "mTLS client authentication bypass",
        "description": "Calls PAR with no client certificate and no client assertion.",
        "reference": "RFC 8705; FAPI 2.0.",
    },
    {
        "check_id": "AUTH-003",
        "title": "Weak client authentication",
        "description": "Attempts client_secret_basic at the PAR endpoint.",
        "reference": "FAPI 2.0 permitted methods.",
    },
    {
        "check_id": "DPOP-001",
        "title": "DPoP proof replay",
        "description": "Replays the same DPoP proof on a second resource request.",
        "reference": "Hosseyni et al. (2025) §3.3.",
    },
    {
        "check_id": "DPOP-002",
        "title": "Malformed DPoP proof",
        "description": "Sends a DPoP proof missing required claims at the token endpoint.",
        "reference": "RFC 9449.",
    },
    {
        "check_id": "MTLS-002",
        "title": "mTLS token binding bypass",
        "description": "Presents an mTLS-bound access token without the matching certificate.",
        "reference": "RFC 8705 cnf.x5t#S256.",
    },
    {
        "check_id": "TOK-001",
        "title": "Unauthenticated introspection",
        "description": "Calls /introspect with no resource-server credentials.",
        "reference": "RFC 7662.",
    },
    {
        "check_id": "TOK-002",
        "title": "RS blind trust in token binding",
        "description": "Presents a sender-constrained token at the RS with no proof of possession.",
        "reference": "Hosseyni et al. (2025) §3.5 Cuckoo's Token Attack.",
    },
    {
        "check_id": "RESP-001",
        "title": "Authorization response iss parameter",
        "description": "Inspects the authorization response for a correct iss parameter.",
        "reference": "RFC 9207 mix-up.",
    },
    {
        "check_id": "RESP-002",
        "title": "Loose redirect_uri matching",
        "description": "Requests authorization with a prefix variant of the registered redirect_uri.",
        "reference": "FAPI 2.0 redirect URI matching.",
    },
    {
        "check_id": "RESP-003",
        "title": "JARM signature",
        "description": "Checks that the JARM authorization response is signed.",
        "reference": "RFC 9101 JARM.",
    },
    {
        "check_id": "DCR-001",
        "title": "Open dynamic client registration",
        "description": "Posts to /register with no initial access token.",
        "reference": "RFC 7591.",
    },
    {
        "check_id": "DCM-001",
        "title": "Unauthenticated client management",
        "description": "Puts /register/{client_id} with no registration access token.",
        "reference": "RFC 7592.",
    },
]
